### PR TITLE
Merge changes regarding HTO script usage with parameters from outside the script.

### PR DESCRIPTION
**Pull request by tglomb**
I changed the HTO script so that the script can be rendered wit parameters set outside the script.  
This should improve automatization of the script and data analysis of a set of samples.

### CODE REVIEW

**Comment by ktrns** [comment]
Hi Torsten. 

Thank you for the PR. 

Andreas and I went through your suggestions this morning, and came up with 3 main questions: 
- Are parameters in the YML header defaults? That is, if you don't specify `paramsList$mt="^MT-"` from outside, would it take the default from the YML header? Have you tested it? 
- Can you think of a good way to keep all parameter descriptions that are currently just comments in the parameter chunk? 
- Rather than converting parameters to text below `## Project-specific parameters`, would you be able to create a table at the end, say above `# Software versions`, and similar to the software table? 

Thanks a lot! 
Katrin

**Comment by tglomb** [comment]
Hi Katrin, hi Andreas,

- Yes, the parameters specified in the YAML header are defaults. If nothing is specified in parameter list defined outside the script then these default value will be set. We could also think about not to set up the obligatory parameters. If something is missing the script could be stopped right at the beginning and return a help/usage message.
- There could be some kind of description in the README as well as a usage message after a short test at the beginning of the script if some parameter is not as expected (HTO names, prefix of mitochondrial genes, etc).
- A parameter table at the end is a good idea and would be a more elegant way of presenting them. I would just leave the project name or so at the top or already include it in the title.

If this seems to be okay for you I can have a look on it to change the script appropriately.

**Comment by ktrns** [comment]
Hi Torsten, 

- Wrt obligatory parameters, it would be nice to hear what Andreas thinks. I believe he liked the idea of having defaults and not having to always define all parameters. 
- Description of all parameters is necessary, and README plus usage message sound good to me. What I like about the current set up is that I can run the R code inside Rstudio for a new project, go through it and finally knit it together. I know that you guys prefer it more automated, but is there a way to keep something similar, i.e. that the script can be started from outside (like you wrote it now), and the script can be run from inside Rstudio (with the parameter chunk as it was before)? 
- Parameter table at the end and project name at the top sound good to me. 

Thanks a lot. Let's see what Andreas thinks.

**Comment by andpet0101** [comment]
Hi,

- I would set all defaults in the `params` section of the YAML header. I tested it with a small script. It works for every scenario: calling knitr from outside, calling knitr from RStudio, calling knitr from RStudio with parameters ("knit with extra parameters") and even when running chunk by chunk. The only question would be how to organise more complex parameters (see input datasets).
- Description in README is okay. I do not know how to comment in the YAML header though. A usage message has lower priority for me and the question is where to write the message to when calling from RStudio. [https://bookdown.org/yihui/rmarkdown/parameterized-reports.html](url) might contain some inspiration.
- Sounds good.

Reminds me: I think the `params` object will be initialised when running the setup chunk. So if we modify it later, then we may need to keep that in mind.

Andreas

**Comment by ktrns** [comment]
This PR was replaced by PR #36.

**Pull request closed without merging**
